name: Backend CI

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Build the backend
      run: |
        cd backend
        npm run build

    - name: Upload backend build artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: backend-build
        path: backend/build  # Adjust this if the build folder is different
