name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        cd frontend
        npm install


    - name: Build the frontend
      run: |
        cd frontend
        npm run build


    - name: Detailed debugging
      run: |
        pwd
        cd frontend
        echo "Current directory contents:"
        ls -la
        echo "Detailed .next directory contents:"
        ls -lR .next
        echo "Finding .next directory:"
        find . -name ".next"
    
    - name: Upload frontend build artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: |
          .next
          !.next/cache
        working-directory: frontend
        if-no-files-found: error
